import {lazy} from 'react';
import {
  KeyIcon,
  FingerPrintIcon,
  IdentificationIcon,
  TicketIcon,
  CodeBracketIcon,
  LinkIcon,
  CodeBracketSquareIcon,
  ClockIcon,
  SwatchIcon,
  DocumentMagnifyingGlassIcon,
  LanguageIcon,
  PhotoIcon,
  LockClosedIcon,
  ShieldExclamationIcon,
  EyeSlashIcon,
  TrashIcon,
  LinkSlashIcon,
  CursorArrowRaysIcon,
  Squares2X2Icon,
  TableCellsIcon,
  EnvelopeIcon,
  EyeIcon,
  ArchiveBoxIcon,
  QrCodeIcon,
  ChartBarIcon,
  GlobeAltIcon,
  DocumentMinusIcon,
  MapPinIcon,
  ShieldCheckIcon,
  DocumentCheckIcon,
  WrenchScrewdriverIcon,
  CommandLineIcon,
  DocumentTextIcon,
  MagnifyingGlassIcon,
  ServerIcon,
  MusicalNoteIcon,
  HashtagIcon,
  DocumentDuplicateIcon,
  CubeIcon,
  PaintBrushIcon,
  EyeDropperIcon,
} from '@heroicons/react/24/outline';
import type {ToolDef, ToolCategory} from './types';

export const CATEGORY_ORDER: ToolCategory[] = [
  'Security',
  'Encoding',
  'Data',
  'Media',
  'Text',
  'Design',
  'Dev',
];

export const TOOLS: ToolDef[] = [
  {
    id: 'password-generator',
    name: 'Password Generator',
    tagline: 'Strong random passwords and passphrases',
    description:
      'Generate cryptographically secure passwords and diceware-style passphrases using your operating system randomness.',
    category: 'Security',
    icon: KeyIcon,
    keywords: ['password', 'passphrase', 'random', 'entropy', 'diceware'],
    component: lazy(() => import('./PasswordGenerator')),
  },
  {
    id: 'password-analyzer',
    name: 'Password Analyzer',
    tagline: 'Score a secret without sending it anywhere',
    description:
      'Estimate password strength from length, character classes, common lists, keyboard walks and 1337 substitutions. Scoring stays in this tab - no breach corpus is queried.',
    category: 'Security',
    icon: ChartBarIcon,
    keywords: ['password', 'strength', 'entropy', 'zxcvbn', 'passphrase', 'privacy', 'offline'],
    component: lazy(() => import('./PasswordAnalyzer')),
  },
  {
    id: 'hash-calculator',
    name: 'Hash Calculator',
    tagline: 'SHA family digests for text and files',
    description:
      'Compute SHA-1, SHA-256, SHA-384 and SHA-512 digests of text or local files to verify integrity without uploading anything.',
    category: 'Security',
    icon: FingerPrintIcon,
    keywords: ['hash', 'sha256', 'sha1', 'checksum', 'digest', 'verify'],
    component: lazy(() => import('./HashCalculator')),
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    tagline: 'Bulk RFC 4122 v4 identifiers',
    description:
      'Create random version-4 UUIDs in bulk with optional formatting variants for logs, fixtures and databases.',
    category: 'Security',
    icon: IdentificationIcon,
    keywords: ['uuid', 'guid', 'identifier', 'random'],
    component: lazy(() => import('./UuidGenerator')),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    tagline: 'Inspect token header and claims',
    description:
      'Decode JSON Web Tokens to inspect the algorithm and payload claims. Decoding happens locally - signature is never verified against a server.',
    category: 'Security',
    icon: TicketIcon,
    keywords: ['jwt', 'token', 'auth', 'claims', 'decode'],
    component: lazy(() => import('./JwtDecoder')),
  },
  {
    id: 'aes-crypt',
    name: 'AES Encrypt / Decrypt',
    tagline: 'Seal text and files with AES-GCM',
    description:
      'Encrypt and decrypt text or local files with a passphrase. Keys are derived in-browser with PBKDF2 and AES-256-GCM - the plaintext never leaves this tab.',
    category: 'Security',
    icon: LockClosedIcon,
    keywords: ['aes', 'encrypt', 'decrypt', 'gcm', 'password', 'cipher', 'seal'],
    component: lazy(() => import('./AesCrypt')),
  },
  {
    id: 'hmac-calculator',
    name: 'HMAC Calculator',
    tagline: 'Authenticate messages with a secret',
    description:
      'Compute HMAC-SHA-256, SHA-384 or SHA-512 of text or a local file using a secret that never leaves this device.',
    category: 'Security',
    icon: ShieldExclamationIcon,
    keywords: ['hmac', 'mac', 'sha256', 'authenticate', 'integrity'],
    component: lazy(() => import('./HmacCalculator')),
  },
  {
    id: 'base64-codec',
    name: 'Base64 Encoder / Decoder',
    tagline: 'UTF-8 safe Base64 in both directions',
    description:
      'Encode text to Base64 or decode Base64 back to text with full Unicode support, entirely offline.',
    category: 'Encoding',
    icon: CodeBracketIcon,
    keywords: ['base64', 'encode', 'decode', 'btoa', 'atob'],
    component: lazy(() => import('./Base64Codec')),
  },
  {
    id: 'url-codec',
    name: 'URL Encoder / Decoder',
    tagline: 'Percent-encoding for components and URIs',
    description:
      'Escape reserved characters for URLs or decode percent-encoded strings, choosing between component and full URI rules.',
    category: 'Encoding',
    icon: LinkIcon,
    keywords: ['url', 'uri', 'percent', 'escape', 'query'],
    component: lazy(() => import('./UrlCodec')),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    tagline: 'Validate, prettify and minify',
    description:
      'Format, minify and validate JSON with precise error reporting. Your data is parsed in memory only.',
    category: 'Data',
    icon: CodeBracketSquareIcon,
    keywords: ['json', 'format', 'pretty', 'minify', 'validate', 'lint'],
    component: lazy(() => import('./JsonFormatter')),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    tagline: 'Unix epoch ⇄ human readable dates',
    description:
      'Convert Unix timestamps (seconds or milliseconds) to ISO 8601, UTC and locale strings - and back.',
    category: 'Data',
    icon: ClockIcon,
    keywords: ['unix', 'epoch', 'timestamp', 'date', 'time', 'iso'],
    component: lazy(() => import('./TimestampConverter')),
  },
  {
    id: 'color-converter',
    name: 'Color Picker',
    tagline: 'Visual picker with HEX, RGB and HSL',
    description:
      'Pick colors visually with a native color input, RGB and HSL sliders, EyeDropper, palette and harmonies. All conversions run locally with live preview and WCAG contrast.',
    category: 'Data',
    icon: SwatchIcon,
    keywords: ['color', 'picker', 'hex', 'rgb', 'hsl', 'palette', 'eyedropper', 'contrast', 'css'],
    component: lazy(() => import('./ColorConverter')),
  },
  {
    id: 'image-metadata-inspector',
    name: 'Image Metadata Inspector',
    tagline: 'Reveal EXIF before you share',
    description:
      'Inspect JPEG metadata - EXIF, GPS coordinates and camera details - locally, so you know exactly what a photo leaks before posting it.',
    category: 'Media',
    icon: PhotoIcon,
    keywords: ['exif', 'metadata', 'jpeg', 'jpg', 'gps', 'photo', 'privacy'],
    component: lazy(() => import('./ImageMetadataInspector')),
  },
  {
    id: 'metadata-remover',
    name: 'Metadata Remover',
    tagline: 'Strip EXIF from images and MP4/MOV metadata',
    description:
      'Remove EXIF, GPS coordinates and camera tags from images, or drop metadata boxes from MP4, M4V and MOV videos - all locally, with no upload.',
    category: 'Media',
    icon: TrashIcon,
    keywords: ['exif', 'metadata', 'remove', 'strip', 'gps', 'mp4', 'mov', 'video', 'privacy', 'clean'],
    component: lazy(() => import('./MetadataRemover')),
  },
  {
    id: 'image-pixelator',
    name: 'Image Pixelator',
    tagline: 'Mosaic faces and secrets before sharing',
    description:
      'Draw a box over faces, plates or tokens and download a censored copy. The region becomes solid mosaic blocks with no blur for software to reverse.',
    category: 'Media',
    icon: Squares2X2Icon,
    keywords: ['pixelate', 'mosaic', 'censor', 'blur', 'redact', 'face', 'screenshot', 'privacy'],
    component: lazy(() => import('./ImagePixelator')),
  },
  {
    id: 'totp-generator',
    name: 'TOTP Generator',
    tagline: 'Offline 2FA codes without a synced app',
    description:
      'Generate RFC 6238 time-based one-time passwords from an otpauth:// URI or Base32 secret. Codes are derived locally with Web Crypto - the secret never reaches a server.',
    category: 'Security',
    icon: CursorArrowRaysIcon,
    keywords: ['totp', '2fa', 'mfa', 'otp', 'authenticator', 'one-time password', 'rfc6238', 'privacy'],
    component: lazy(() => import('./TotpGenerator')),
  },
  {
    id: 'link-cleaner',
    name: 'Link Cleaner',
    tagline: 'Strip tracking parameters before sharing URLs',
    description:
      'Remove utm_*, fbclid, gclid and dozens of other click-identifiers from links. Paste one URL or a batch; cleaned links are rebuilt in your browser.',
    category: 'Security',
    icon: LinkSlashIcon,
    keywords: ['url', 'tracking', 'utm', 'fbclid', 'gclid', 'clean', 'share', 'privacy'],
    component: lazy(() => import('./LinkCleaner')),
  },
  {
    id: 'homograph-detector',
    name: 'Homograph Detector',
    tagline: 'Spot lookalike letters in URLs and emails',
    description:
      'Reveal mixed scripts, punycode, zero-width characters and Cyrillic/Greek lookalikes that spoof Latin letters. Comparison uses local Unicode data - nothing is resolved on the network.',
    category: 'Security',
    icon: GlobeAltIcon,
    keywords: ['homograph', 'idn', 'punycode', 'phishing', 'lookalike', 'cyrillic', 'unicode', 'privacy'],
    component: lazy(() => import('./HomographDetector')),
  },
  {
    id: 'fingerprint-panel',
    name: 'Browser Fingerprint Panel',
    tagline: 'See what your browser reveals about you',
    description:
      'Inspect the canvas, WebGL, audio, hardware and preference signals that fingerprinting scripts read. A local mirror only - nothing is reported anywhere.',
    category: 'Security',
    icon: EyeSlashIcon,
    keywords: ['fingerprint', 'canvas', 'webgl', 'audio', 'tracking', 'browser', 'entropy', 'privacy'],
    component: lazy(() => import('./FingerprintPanel')),
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    tagline: 'Compare two texts line by line',
    description:
      'Spot added, removed and unchanged lines between two versions of a text using a classic longest-common-subsequence diff.',
    category: 'Text',
    icon: DocumentMagnifyingGlassIcon,
    keywords: ['diff', 'compare', 'changes', 'text'],
    component: lazy(() => import('./TextDiff')),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    tagline: 'camelCase, snake_case, kebab and more',
    description:
      'Convert text between camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, Title Case and sentence case.',
    category: 'Text',
    icon: LanguageIcon,
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'title'],
    component: lazy(() => import('./CaseConverter')),
  },
  {
    id: 'secret-redactor',
    name: 'Secret Redactor',
    tagline: 'Mask emails, tokens and keys before you share',
    description:
      'Replace emails, phone numbers, JWTs, API tokens, card numbers and private keys in text so you can paste logs or tickets without leaking secrets.',
    category: 'Text',
    icon: EyeSlashIcon,
    keywords: ['redact', 'pii', 'email', 'token', 'secret', 'sanitize', 'mask'],
    component: lazy(() => import('./SecretRedactor')),
  },
  {
    id: 'csv-anonymizer',
    name: 'CSV / JSON Anonymizer',
    tagline: 'Anonymize spreadsheets without breaking joins',
    description:
      'Anonymize CSV and JSON datasets locally: pseudonymize, mask, hash or remove columns. Same salt → same pseudonyms, so joins stay consistent. Everything runs in this tab.',
    category: 'Data',
    icon: TableCellsIcon,
    keywords: ['anonymize', 'pseudonymize', 'csv', 'json', 'gdpr', 'lgpd', 'privacy', 'dataset'],
    component: lazy(() => import('./CsvAnonymizer')),
  },
  {
    id: 'location-anonymizer',
    name: 'Location Track Anonymizer',
    tagline: 'Fuzz GPX and GeoJSON before you publish',
    description:
      'Round and shift coordinates, drop timestamps, elevation and names from GPX or GeoJSON tracks. Everything runs locally - no map tiles are fetched.',
    category: 'Data',
    icon: MapPinIcon,
    keywords: ['gpx', 'geojson', 'gps', 'anonymize', 'track', 'location', 'privacy', 'fuzz'],
    component: lazy(() => import('./LocationAnonymizer')),
  },
  {
    id: 'email-privacy-inspector',
    name: 'Email Privacy Inspector',
    tagline: 'Reveal hidden pixels and spoofing signals',
    description:
      'Paste raw email source to detect 1×1 tracking pixels, Reply-To mismatches, bulk-mail flags and link trackers. Parsed locally with DOMParser and regex - never sent.',
    category: 'Security',
    icon: EnvelopeIcon,
    keywords: ['email', 'pixel', 'tracking', 'spoof', 'dkim', 'spf', 'privacy', 'eml'],
    component: lazy(() => import('./EmailPrivacyInspector')),
  },
  {
    id: 'tracker-inspector',
    name: 'Tracker Inspector',
    tagline: 'Audit HTML for pixels, scripts and beacons',
    description:
      'Paste HTML from newsletters or landing pages to enumerate tracking pixels, third-party scripts, hidden iframes and utm_*/fbclid links. Sanitize locally before sharing.',
    category: 'Security',
    icon: EyeIcon,
    keywords: ['tracker', 'pixel', 'html', 'sanitize', 'utm', 'privacy', 'beacon', 'script'],
    component: lazy(() => import('./TrackerInspector')),
  },
  {
    id: 'har-sanitizer',
    name: 'HAR Sanitizer',
    tagline: 'Redact cookies, tokens and IPs from captures',
    description:
      'Strip cookies, Authorization headers, query tokens, JWTs, PEM keys and IP addresses from HAR or JSON captures before you attach them to a ticket. Parsing stays in this tab.',
    category: 'Security',
    icon: DocumentMinusIcon,
    keywords: ['har', 'sanitize', 'redact', 'cookie', 'authorization', 'devtools', 'capture', 'privacy'],
    component: lazy(() => import('./HarSanitizer')),
  },
  {
    id: 'cookie-inspector',
    name: 'Cookie Inspector',
    tagline: 'Audit cookie flags without exposing their values',
    description:
      'Inspect Cookie and Set-Cookie headers for tracking-like names, Secure, HttpOnly, SameSite, domain scope and long retention. Values are never rendered in the results and nothing leaves this tab.',
    category: 'Security',
    icon: ShieldCheckIcon,
    keywords: ['cookie', 'set-cookie', 'samesite', 'httponly', 'secure', 'tracking', 'privacy', 'header'],
    component: lazy(() => import('./CookieInspector')),
  },
  {
    id: 'privacy-header-inspector',
    name: 'Privacy Header Inspector',
    tagline: 'Review privacy-related HTTP response headers',
    description:
      'Analyze pasted HTTP response headers for referrer leakage, Permissions-Policy, CSP, caching, CORS and server disclosure. The review is local and does not contact the URL.',
    category: 'Security',
    icon: DocumentCheckIcon,
    keywords: ['http', 'header', 'csp', 'cors', 'referrer-policy', 'permissions-policy', 'cache-control', 'privacy'],
    component: lazy(() => import('./PrivacyHeaderInspector')),
  },
  {
    id: 'paste-vault',
    name: 'Paste Vault',
    tagline: 'Seal notes with a passphrase, share via fragment',
    description:
      'Encrypt a note with AES-256-GCM + PBKDF2 and share it as a URL fragment that never reaches a server. Decryption happens entirely in the recipient tab.',
    category: 'Security',
    icon: ArchiveBoxIcon,
    keywords: ['vault', 'encrypt', 'paste', 'share', 'aes', 'fragment', 'privacy', 'seal'],
    component: lazy(() => import('./PasteVault')),
  },
  {
    id: 'qr-studio',
    name: 'QR Studio',
    tagline: 'Generate and scan QR codes offline',
    description:
      'Create QR codes for URLs, WiFi, Pix or secrets on a Canvas and scan QR images with jsQR - both bundled and offline. No external API ever sees your data.',
    category: 'Media',
    icon: QrCodeIcon,
    keywords: ['qr', 'qrcode', 'scan', 'wifi', 'pix', 'offline', 'privacy', 'canvas'],
    component: lazy(() => import('./QrStudio')),
  },
  {
    id: 'sri-generator',
    name: 'SRI Generator',
    tagline: 'Generate Subresource Integrity hashes offline',
    description:
      'Compute SHA-256/384/512 digests for files or text and emit integrity="sha384-..." attributes. All hashing uses Web Crypto in this tab — no upload to a CDN checker.',
    category: 'Security',
    icon: ShieldCheckIcon,
    keywords: ['sri', 'integrity', 'sha256', 'sha384', 'csp', 'cdn', 'hash', 'offline'],
    component: lazy(() => import('./SriGenerator')),
  },
  {
    id: 'csp-builder',
    name: 'CSP Builder',
    tagline: 'Craft Content-Security-Policy headers locally',
    description:
      'Assemble CSP directives, generate nonces, and preview the header and meta tag. Validates against common pitfalls — all offline, no server check.',
    category: 'Security',
    icon: DocumentCheckIcon,
    keywords: ['csp', 'content-security-policy', 'header', 'nonce', 'security', 'privacy'],
    component: lazy(() => import('./CspBuilder')),
  },
  {
    id: 'curl-scrubber',
    name: 'cURL Scrubber',
    tagline: 'Redact secrets from cURL and fetch snippets',
    description:
      'Paste cURL, HTTPie, or fetch commands to strip Authorization, cookies, query tokens, JWTs and IPs. Parsing is local regex — complements HAR Sanitizer for raw snippets.',
    category: 'Security',
    icon: CommandLineIcon,
    keywords: ['curl', 'httpie', 'fetch', 'scrub', 'redact', 'authorization', 'cookie', 'har', 'privacy'],
    component: lazy(() => import('./CurlScrubber')),
  },
  {
    id: 'cert-inspector',
    name: 'Certificate Inspector',
    tagline: 'Decode X.509 certificates offline',
    description:
      'Paste a PEM certificate or CSR to reveal subject, SANs, validity, signature algorithm, public key type and SHA-256 fingerprint. Decoded with Web Crypto and a local parser — no OCSP lookup.',
    category: 'Security',
    icon: DocumentMagnifyingGlassIcon,
    keywords: ['certificate', 'x509', 'pem', 'csr', 'tls', 'fingerprint', 'san', 'privacy'],
    component: lazy(() => import('./CertInspector')),
  },
  {
    id: 'env-scrubber',
    name: 'Env Scrubber',
    tagline: 'Audit .env and config files for secrets',
    description:
      'Scan .env, docker-compose, or INI text for keys like SECRET_KEY or API_KEY and mask their values. Detects high-entropy tokens and PEM blocks — all in this tab.',
    category: 'Security',
    icon: WrenchScrewdriverIcon,
    keywords: ['env', 'dotenv', 'config', 'secret', 'api-key', 'scrub', 'redact', 'privacy'],
    component: lazy(() => import('./EnvScrubber')),
  },
  {
    id: 'auth-header-studio',
    name: 'Auth Header Studio',
    tagline: 'Build and decode Authorization headers',
    description:
      'Create Basic (user:pass → Base64) and Bearer headers or decode a Basic header. Encodes with TextEncoder and atob/btoa locally — never sent.',
    category: 'Security',
    icon: LockClosedIcon,
    keywords: ['auth', 'authorization', 'basic', 'bearer', 'base64', 'header', 'privacy'],
    component: lazy(() => import('./AuthHeaderStudio')),
  },
  {
    id: 'svg-sanitizer',
    name: 'SVG Sanitizer',
    tagline: 'Strip scripts and event handlers from SVG',
    description:
      'Remove <script>, foreignObject, iframes, on* handlers and javascript: URLs from SVG via DOMParser. Download a clean copy — nothing leaves this tab.',
    category: 'Media',
    icon: EyeSlashIcon,
    keywords: ['svg', 'sanitize', 'xss', 'script', 'sanitizer', 'privacy', 'clean'],
    component: lazy(() => import('./SvgSanitizer')),
  },
  {
    id: 'pdf-inspector',
    name: 'PDF Inspector',
    tagline: 'Reveal and remove PDF metadata',
    description:
      'Read Info dictionary (Author, Creator, dates) and XMP streams from PDFs, then strip them locally. Byte scan in this tab — no upload.',
    category: 'Media',
    icon: DocumentTextIcon,
    keywords: ['pdf', 'metadata', 'xmp', 'info', 'clean', 'privacy', 'strip'],
    component: lazy(() => import('./PdfInspector')),
  },
  {
    id: 'audio-tag-cleaner',
    name: 'Audio Tag Cleaner',
    tagline: 'Strip ID3 tags from MP3 locally',
    description:
      'Inspect ID3v2/ID3v1 frames (artist, album, cover art) and slice them off byte-for-byte. Audio frames stay untouched — no re-encoding, no upload.',
    category: 'Media',
    icon: MusicalNoteIcon,
    keywords: ['audio', 'mp3', 'id3', 'tag', 'metadata', 'clean', 'privacy'],
    component: lazy(() => import('./AudioTagCleaner')),
  },
  {
    id: 'file-magic-inspector',
    name: 'File Magic Inspector',
    tagline: 'Detect real file type from magic bytes',
    description:
      'Read the first 32 bytes via FileReader to reveal true MIME vs extension. Catches spoofed double extensions like invoice.pdf.exe — offline via DataView.',
    category: 'Data',
    icon: MagnifyingGlassIcon,
    keywords: ['magic', 'mime', 'file', 'spoof', 'extension', 'phishing', 'privacy'],
    component: lazy(() => import('./FileMagicInspector')),
  },
  {
    id: 'regex-lab',
    name: 'Regex Lab',
    tagline: 'Test regular expressions offline',
    description:
      'Try patterns and flags against your own text with live match highlighting and replace preview. Ideal for crafting PII redaction regex without sending samples to an online tester.',
    category: 'Text',
    icon: CodeBracketSquareIcon,
    keywords: ['regex', 'regexp', 'pattern', 'test', 'match', 'pii', 'privacy'],
    component: lazy(() => import('./RegexLab')),
  },
  {
    id: 'invisible-char-detector',
    name: 'Invisible Character Detector',
    tagline: 'Reveal zero-width and bidi characters',
    description:
      'Scan text for zero-width spaces, joiners, BOM, variation selectors and bidi overrides (RLO/LRI) that spoof filenames or hide tracking. Visualize and strip them locally.',
    category: 'Text',
    icon: EyeIcon,
    keywords: ['invisible', 'zero-width', 'bidi', 'unicode', 'spoof', 'privacy', 'rlo'],
    component: lazy(() => import('./InvisibleCharDetector')),
  },
  {
    id: 'pii-risk-scanner',
    name: 'PII Risk Scanner',
    tagline: 'Score a document for PII exposure',
    description:
      'Scan free-text for emails, phones, cards, JWTs, PEM keys, IPs and IBAN patterns and compute a risk score. Detection only — no replacement, no upload.',
    category: 'Text',
    icon: ShieldExclamationIcon,
    keywords: ['pii', 'risk', 'scan', 'email', 'phone', 'card', 'iban', 'privacy'],
    component: lazy(() => import('./PiiRiskScanner')),
  },
  {
    id: 'free-text-pseudonymizer',
    name: 'Free-Text Pseudonymizer',
    tagline: 'Pseudonymize prose while keeping it readable',
    description:
      'Replace emails, phones, and IPs in unstructured text with deterministic pseudonyms (same salt → same anon). Keeps co-reference for tickets and logs — all local FNV-1a hashing.',
    category: 'Text',
    icon: DocumentDuplicateIcon,
    keywords: ['pseudonymize', 'anonymize', 'free-text', 'pii', 'gdpr', 'privacy', 'salt'],
    component: lazy(() => import('./FreeTextPseudonymizer')),
  },
  {
    id: 'markdown-sanitizer',
    name: 'Markdown Sanitizer',
    tagline: 'Preview Markdown and flag trackers',
    description:
      'Render Markdown locally and list external images (IP leak), tracking params (utm/fbclid), iframes and script tags via DOMParser — no fetch.',
    category: 'Text',
    icon: DocumentTextIcon,
    keywords: ['markdown', 'sanitize', 'tracker', 'preview', 'utm', 'privacy', 'html'],
    component: lazy(() => import('./MarkdownSanitizer')),
  },
  {
    id: 'jsonl-toolkit',
    name: 'JSONL Toolkit',
    tagline: 'Validate and filter JSON Lines locally',
    description:
      'Parse NDJSON/JSONL line-by-line, report errors, filter by key=value or substring, and convert between JSONL and JSON array — all in memory, no upload.',
    category: 'Data',
    icon: TableCellsIcon,
    keywords: ['jsonl', 'ndjson', 'json', 'filter', 'validate', 'privacy', 'lines'],
    component: lazy(() => import('./JsonlToolkit')),
  },
  {
    id: 'log-anonymizer',
    name: 'Log Anonymizer',
    tagline: 'Anonymize Apache/Nginx log lines',
    description:
      'Scrub IPs, user-agents, query secrets, emails and JWTs from access log lines. Choose redact/hash/mask per field with a salt for consistent pseudonyms — local only.',
    category: 'Data',
    icon: ServerIcon,
    keywords: ['log', 'apache', 'nginx', 'anonymize', 'ip', 'ua', 'privacy', 'access'],
    component: lazy(() => import('./LogAnonymizer')),
  },
  {
    id: 'sql-anonymizer',
    name: 'SQL Anonymizer',
    tagline: 'Mask INSERT VALUES before sharing dumps',
    description:
      'Rewrite INSERT INTO ... VALUES tuples: pseudonymize, hash, mask or redact per column. Deterministic with salt — best-effort parser for simple dumps, local only.',
    category: 'Data',
    icon: CubeIcon,
    keywords: ['sql', 'dump', 'anonymize', 'insert', 'database', 'privacy', 'gdpr'],
    component: lazy(() => import('./SqlAnonymizer')),
  },
  {
    id: 'ulid-generator',
    name: 'ULID Generator',
    tagline: 'Generate sortable ULID / KSUID offline',
    description:
      'Create time-ordered, privacy-safe IDs with crypto.getRandomValues. Crockford Base32 — monotonic per batch, no PII, no server.',
    category: 'Encoding',
    icon: HashtagIcon,
    keywords: ['ulid', 'ksuid', 'id', 'sortable', 'random', 'privacy', 'crockford'],
    component: lazy(() => import('./UlidGenerator')),
  },
  {
    id: 'text-encoding-lab',
    name: 'Text Encoding Lab',
    tagline: 'Convert HTML, URL, Base64, Unicode locally',
    description:
      'Encode/decode between HTML entities, URL percent-encoding, Base64, Unicode escapes and Quoted-Printable with TextEncoder/DOMParser — plus mojibake detection.',
    category: 'Encoding',
    icon: LanguageIcon,
    keywords: ['encoding', 'html', 'url', 'base64', 'unicode', 'quoted-printable', 'privacy'],
    component: lazy(() => import('./TextEncodingLab')),
  },
  {
    id: 'palette-extractor',
    name: 'Palette Extractor',
    tagline: 'Extract dominant colors from any image',
    description:
      'Sample pixels via Canvas and cluster with k-means to reveal 6 dominant colors. Exports HEX, CSS vars, and Tailwind config — all offline, no upload.',
    category: 'Design',
    icon: SwatchIcon,
    keywords: ['palette', 'color', 'dominant', 'k-means', 'image', 'theme', 'offline'],
    component: lazy(() => import('./PaletteExtractor')),
  },
  {
    id: 'gradient-studio',
    name: 'Gradient Studio',
    tagline: 'Build CSS gradients live',
    description:
      'Craft linear, radial, and conic gradients with live preview and copy-ready CSS. All computed locally with Canvas preview.',
    category: 'Design',
    icon: PaintBrushIcon,
    keywords: ['gradient', 'css', 'linear', 'radial', 'conic', 'background', 'design'],
    component: lazy(() => import('./GradientStudio')),
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    tagline: 'WCAG ratio with daltonism simulation',
    description:
      'Check WCAG AA/AAA contrast with luminance math and preview protanopia, deuteranopia, and tritanopia simulations. Local only, no audit service.',
    category: 'Design',
    icon: EyeDropperIcon,
    keywords: ['contrast', 'wcag', 'a11y', 'accessibility', 'daltonism', 'color', 'ratio'],
    component: lazy(() => import('./ContrastChecker')),
  },
  {
    id: 'type-scale-studio',
    name: 'Type Scale Studio',
    tagline: 'Modular scale with fluid clamp()',
    description:
      'Generate a modular type scale and fluid clamp() values for responsive typography. Copy CSS vars and preview sizes — offline.',
    category: 'Design',
    icon: DocumentTextIcon,
    keywords: ['typography', 'scale', 'clamp', 'fluid', 'css', 'font', 'modular'],
    component: lazy(() => import('./TypeScaleStudio')),
  },
  {
    id: 'shadow-radius-studio',
    name: 'Shadow & Radius Studio',
    tagline: 'Box-shadow and radius playground',
    description:
      'Tweak x, y, blur, spread, and radius with live card preview. Copy box-shadow and border-radius CSS — all local.',
    category: 'Design',
    icon: CubeIcon,
    keywords: ['shadow', 'radius', 'css', 'box-shadow', 'border', 'design', 'card'],
    component: lazy(() => import('./ShadowRadiusStudio')),
  },
  {
    id: 'grid-builder',
    name: 'Grid Builder',
    tagline: 'Visual CSS Grid builder',
    description:
      'Configure columns, rows, and gaps visually and copy grid-template CSS with HTML. Preview updates live — no layout cloud.',
    category: 'Design',
    icon: Squares2X2Icon,
    keywords: ['grid', 'css', 'layout', 'template', 'gap', 'design', 'responsive'],
    component: lazy(() => import('./GridBuilder')),
  },
  {
    id: 'favicon-studio',
    name: 'Favicon Studio',
    tagline: 'Generate favicons/OG from logo',
    description:
      'Re-encode a logo via Canvas to 16/32/48/180/192/512 PNGs and pack a multi-size favicon.ico. No image leaves this tab.',
    category: 'Design',
    icon: PhotoIcon,
    keywords: ['favicon', 'ico', 'png', 'icon', 'og', 'pwa', 'logo'],
    component: lazy(() => import('./FaviconStudio')),
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    tagline: 'Optimize SVG without cloud',
    description:
      'Strip comments and metadata, round coordinates, and remove editor cruft from SVG locally. Reports saved bytes — no SVGO cloud.',
    category: 'Design',
    icon: WrenchScrewdriverIcon,
    keywords: ['svg', 'optimize', 'minify', 'svgo', 'vector', 'clean', 'offline'],
    component: lazy(() => import('./SvgOptimizer')),
  },
  // Dev — 20 programming tools
  {
    id: 'yaml-converter',
    name: 'YAML Converter',
    tagline: 'YAML ↔ JSON sem vazar configs',
    description:
      'Converta YAML para JSON e vice-versa localmente. Evita enviar application.yaml com secrets para conversores online. Parser cobre mappings e sequências comuns.',
    category: 'Dev',
    icon: CodeBracketIcon,
    keywords: ['yaml', 'json', 'convert', 'config', 'offline', 'privacy'],
    component: lazy(() => import('./YamlConverter')),
  },
  {
    id: 'toml-converter',
    name: 'TOML Converter',
    tagline: 'TOML ↔ JSON offline',
    description:
      'Transforme Cargo.toml, pyproject.toml e configs TOML em JSON localmente, sem expor estrutura interna.',
    category: 'Dev',
    icon: DocumentDuplicateIcon,
    keywords: ['toml', 'json', 'cargo', 'pyproject', 'convert', 'offline'],
    component: lazy(() => import('./TomlConverter')),
  },
  {
    id: 'xml-converter',
    name: 'XML Converter',
    tagline: 'XML ↔ JSON via DOMParser',
    description:
      'Converta SOAP/RSS e XML genérico para JSON usando DOMParser nativo. Nenhum envelope com PII sai do browser.',
    category: 'Dev',
    icon: CodeBracketSquareIcon,
    keywords: ['xml', 'json', 'convert', 'soap', 'domparser', 'offline'],
    component: lazy(() => import('./XmlConverter')),
  },
  {
    id: 'json-schema-validator',
    name: 'JSON Schema Validator',
    tagline: 'Valide payloads contra schema',
    description:
      'Valide JSON contra JSON Schema sem enviar schema proprietário. Cobre type, required, properties, enum e constraints comuns.',
    category: 'Dev',
    icon: DocumentCheckIcon,
    keywords: ['json', 'schema', 'validate', 'ajv', 'offline', 'privacy'],
    component: lazy(() => import('./JsonSchemaValidator')),
  },
  {
    id: 'jsonpath-tester',
    name: 'JSONPath Tester',
    tagline: 'Teste JSONPath offline',
    description:
      'Teste expressões JSONPath ($, ., [], [*]) contra seu JSON privado. Evita colar dados de clientes em testadores online.',
    category: 'Dev',
    icon: MagnifyingGlassIcon,
    keywords: ['jsonpath', 'jmespath', 'json', 'query', 'offline', 'privacy'],
    component: lazy(() => import('./JsonPathTester')),
  },
  {
    id: 'jwt-builder',
    name: 'JWT Builder & Signer',
    tagline: 'Assine HS256/384/512 local',
    description:
      'Construa e assine JWTs com HMAC-SHA via Web Crypto. Segredo nunca sai do tab — alternativa privada ao jwt.io.',
    category: 'Dev',
    icon: TicketIcon,
    keywords: ['jwt', 'jws', 'hs256', 'sign', 'hmac', 'offline', 'privacy'],
    component: lazy(() => import('./JwtBuilder')),
  },
  {
    id: 'hex-inspector',
    name: 'Hex Inspector',
    tagline: 'Hex ↔ Texto e hex dump',
    description:
      'Converta texto para hex, hex para texto e gere hex dump estilo xxd. Arquivos lidos via FileReader, nunca enviados.',
    category: 'Dev',
    icon: CommandLineIcon,
    keywords: ['hex', 'dump', 'xxd', 'binary', 'offline', 'privacy'],
    component: lazy(() => import('./HexInspector')),
  },
  {
    id: 'unicode-inspector',
    name: 'Unicode Inspector',
    tagline: 'Codepoints, UTF-8, NFC/NFD',
    description:
      'Inspecione codepoints, bytes UTF-8 e normalizações. Detecta mojibake. Tudo via TextEncoder local.',
    category: 'Dev',
    icon: LanguageIcon,
    keywords: ['unicode', 'utf8', 'codepoint', 'nfc', 'nfd', 'offline'],
    component: lazy(() => import('./UnicodeInspector')),
  },
  {
    id: 'code-beautifier',
    name: 'Code Beautifier',
    tagline: 'HTML/CSS/JS/JSON com 2 engines',
    description:
      'Formate e minifique HTML, CSS, JS e JSON offline. Engine Fast (regex leve) e Pretty (fiel), ambos sem upload.',
    category: 'Dev',
    icon: PaintBrushIcon,
    keywords: ['beautify', 'format', 'minify', 'prettier', 'html', 'css', 'js', 'offline'],
    component: lazy(() => import('./CodeBeautifier')),
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    tagline: 'Formate SQL offline',
    description:
      'Formate e minifique SQL com keywords em maiúsculas e quebras por cláusula. Evita enviar dumps com PII para formatadores online.',
    category: 'Dev',
    icon: CubeIcon,
    keywords: ['sql', 'format', 'pretty', 'minify', 'offline', 'privacy'],
    component: lazy(() => import('./SqlFormatter')),
  },
  {
    id: 'cron-builder',
    name: 'Cron Builder',
    tagline: 'Monte e explique crons',
    description:
      'Monte expressões cron 5 campos, valide e veja próximas execuções. Explicação humana PT-BR, tudo local.',
    category: 'Dev',
    icon: ClockIcon,
    keywords: ['cron', 'schedule', 'builder', 'explain', 'offline'],
    component: lazy(() => import('./CronBuilder')),
  },
  {
    id: 'curl-codegen',
    name: 'cURL to Code',
    tagline: 'cURL → fetch / Python / Go',
    description:
      'Converta cURL para fetch, Python requests e Go http sem mandar Authorization para conversores online.',
    category: 'Dev',
    icon: CommandLineIcon,
    keywords: ['curl', 'fetch', 'python', 'go', 'codegen', 'offline', 'privacy'],
    component: lazy(() => import('./CurlCodegen')),
  },
  {
    id: 'openapi-preview',
    name: 'OpenAPI Preview',
    tagline: 'Preview leve de specs',
    description:
      'Liste paths, methods e schemas de OpenAPI/Swagger YAML/JSON localmente. Sem upload de spec confidencial.',
    category: 'Dev',
    icon: DocumentMagnifyingGlassIcon,
    keywords: ['openapi', 'swagger', 'api', 'preview', 'yaml', 'offline'],
    component: lazy(() => import('./OpenApiPreview')),
  },
  {
    id: 'graphql-formatter',
    name: 'GraphQL Formatter',
    tagline: 'Formate e valide GraphQL',
    description:
      'Formate queries GraphQL e valide balanceamento de chaves. Mantém schema interno offline.',
    category: 'Dev',
    icon: CodeBracketSquareIcon,
    keywords: ['graphql', 'format', 'query', 'validate', 'offline'],
    component: lazy(() => import('./GraphqlFormatter')),
  },
  {
    id: 'env-transcoder',
    name: '.env Transcoder',
    tagline: '.env ↔ JSON ↔ YAML',
    description:
      'Transcodifique .env para JSON/YAML e vice-versa. Complementa Env Scrubber — não mascara, apenas converte local.',
    category: 'Dev',
    icon: WrenchScrewdriverIcon,
    keywords: ['env', 'dotenv', 'json', 'yaml', 'transcode', 'offline', 'privacy'],
    component: lazy(() => import('./EnvTranscoder')),
  },
  {
    id: 'semver-checker',
    name: 'SemVer Checker',
    tagline: 'Compare e teste ranges',
    description:
      'Compare versões SemVer e teste ranges (^, ~, >=). Ideal para package.json sem consultar serviço externo.',
    category: 'Dev',
    icon: HashtagIcon,
    keywords: ['semver', 'version', 'range', 'compare', 'offline'],
    component: lazy(() => import('./SemverChecker')),
  },
  {
    id: 'keypair-generator',
    name: 'Key Pair Generator',
    tagline: 'RSA/EC via Web Crypto',
    description:
      'Gere pares RSA-2048/4096 e EC P-256/P-384 via Web Crypto e exporte PEM. Chave privada nunca sai do tab.',
    category: 'Dev',
    icon: KeyIcon,
    keywords: ['keypair', 'rsa', 'ec', 'pem', 'webcrypto', 'offline', 'privacy'],
    component: lazy(() => import('./KeypairGenerator')),
  },
  {
    id: 'query-builder',
    name: 'Query String Builder',
    tagline: 'Monte e parseie query strings',
    description:
      'Monte URLs com query params e parseie URLs existentes usando URLSearchParams nativo. Tokens em query ficam locais.',
    category: 'Dev',
    icon: LinkIcon,
    keywords: ['query', 'url', 'searchparams', 'builder', 'parser', 'offline'],
    component: lazy(() => import('./QueryBuilder')),
  },
  {
    id: 'header-builder',
    name: 'HTTP Header Builder',
    tagline: 'Monte headers + atlas de status',
    description:
      'Monte headers HTTP, gere cURL e consulte atlas de status codes. Nenhum header com token é enviado.',
    category: 'Dev',
    icon: DocumentCheckIcon,
    keywords: ['header', 'http', 'status', 'curl', 'authorization', 'offline'],
    component: lazy(() => import('./HeaderBuilder')),
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    tagline: 'Diff estrutural de JSON',
    description:
      'Compare dois JSONs estruturalmente, ignorando ordem de chaves. Ideal para diff de configs prod vs staging.',
    category: 'Dev',
    icon: DocumentMagnifyingGlassIcon,
    keywords: ['json', 'diff', 'compare', 'structural', 'offline', 'privacy'],
    component: lazy(() => import('./JsonDiff')),
  },
];

export function findTool(id: string): ToolDef | undefined {
  return TOOLS.find(tool => tool.id === id);
}
